[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
shipment_sc = "37oMYvqhv2jsMbQw8ZPKKfxmRvFwvRyi6joH5ueP8mAr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./keys/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
